apiVersion: resourcecontrollerv2.ibm-cloud.crossplane.io/v1alpha1
kind: ResourceInstance
metadata:
  name: caine-postgresql
spec:
  forProvider:
    name: caine-postgresql
    target: us-south
    resourceGroupName: default
    serviceName: databases-for-postgresql
    resourcePlanName: standard
    tags:
      - dev
      - caine
    parameters:
      members_disk_allocation_mb: 32768
  providerConfigRef:
    name: ibm-cloud